# Generated by Django 2.2.3 on 2019-09-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
