# Generated by Django 2.2.3 on 2019-09-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='icons',
            new_name='icon',
        ),
    ]
